[package]
name = "topos-telemetry"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
tonic.workspace = true

serde = { workspace = true, features = ["derive", "std"] }
