[package]
name = "topos-telemetry"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
tonic.workspace = true

serde = { workspace = true, features = ["derive", "std"] }
