[package]
name = "topos-metrics"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
futures.workspace = true
lazy_static.workspace = true
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
