[package]
name = "topos-tce"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.64"

# our main binary
[[bin]]
name = "topos-tce-app"
path = "src/tce_node_app.rs"

[dependencies]
# external dependencies
bincode = "1.3.3"
clap = { version = "3.0.10", features = ["derive", "env"] }
libp2p = { version = "0.46", features = ["tcp-tokio"] }
lazy_static = "1.4"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
pretty_env_logger = "0.4.0"
# tce dependencies
tce_store = { package = "topos-tce-store", path = "./crates/topos-tce-store" }
tce_telemetry = { package = "topos-tce-telemetry", path = "./crates/topos-tce-telemetry" }
topos-tce-broadcast = { path = "./crates/topos-tce-broadcast" }
tce_transport = { package = "topos-tce-transport", path = "./crates/topos-tce-transport" }
topos-p2p = { path = "./crates/topos-p2p" }
topos-tce-api = { path = "./crates/topos-tce-api"}

tokio.workspace = true
futures.workspace = true
async-trait.workspace = true
topos-core.workspace = true
serde.workspace = true

[dev-dependencies]
async-trait.workspace = true
cucumber = "0.13.0"
hyper = { version = "0.14", features = ["full"] }
rand_distr = "0.4.1"
rand_core = "0.6.0"
rand = "0.8.5"
env_logger = "*"
test-log = { version = "0.2", features = ["log", "trace"] }
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
tracing.workspace = true

# Commented because the test isn't compatible with gRPC health_check
# [[test]]
# name = "example" # this should be the same as the filename of your test target
# harness = false  # allows Cucumber to print output instead of libtest

[workspace]
members = [
    "crates/*"
]

[workspace.dependencies]
topos-core = { git = "https://github.com/toposware/topos-core", branch = "main", default-features = false, version = "0.1.0" }
tokio = { version = "1.20", default-features = false }
futures = { version = "0.3", default-features = false }
thiserror = { version = "1.0", default-features = false }
async-trait = { version = "0.1", default-features = false }
serde = { version = "1.0", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
