[package]
name = "topos-tce"
version = "0.1.0"
edition = "2021"
license = "MIT"

# our main binary
[[bin]]
name = "topos-tce-node-app"
path = "src/tce_node_app.rs"

[dependencies]
# external dependencies
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "3.0.10", features = ["derive", "env"] }
libp2p = { version = "0.41.0", features = ["tcp-tokio"] }
lazy_static = "1.4"
log = "0.4.14"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
pretty_env_logger = "0.4.0"
tokio = { version = "1.20.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
    "sync",
] }

# tce dependencies
tce_net = { package = "topos-tce-node-net", path = "node/net" }
tce_api = { package = "topos-tce-node-api", path = "node/api" }
tce_store = { package = "topos-tce-node-store", path = "node/store" }
tce_telemetry = { package = "topos-tce-node-telemetry", path = "node/telemetry" }
tce_trbp = { package = "topos-tce-protocols-reliable-broadcast", path = "protocols/reliable_broadcast" }
tce_transport = { package = "topos-tce-protocols-transport", path = "protocols/transport" }

[dev-dependencies]
async-trait = "0.1"
cucumber = "0.13.0"
hyper = { version = "0.14", features = ["full"] }

[[test]]
name = "example" # this should be the same as the filename of your test target
harness = false  # allows Cucumber to print output instead of libtest

[workspace]
members = [
    "node/api",
    "node/net",
    "node/store",
    "node/telemetry",
    "protocols/reliable_broadcast",
    "protocols/transport",
    "params-minimizer",
]
