[workspace]
default-members = ["crates/topos-tce"]
members = [
    "crates/*"
]

[workspace.dependencies]
async-trait = { version = "0.1", default-features = false }
futures = { version = "0.3", default-features = false }
libp2p = { version = "0.47", default-features = false, features = ["noise"]}
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_distr = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1.20", default-features = false }
tokio-stream = { version = "0.1", default-features = false}
tonic = { version = "0.8.0", default-features = false }
topos-core = { git = "https://github.com/toposware/topos-core", branch = "main", default-features = false, version = "0.1.0" }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
