[workspace]
default-members = ["crates/topos"]
members = [
    "crates/*"
]

[workspace.dependencies]
async-trait = { version = "0.1", default-features = false }
futures = { version = "0.3" }
libp2p = { version = "0.49", default-features = false, features = ["noise"]}
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_distr = { version = "0.4", default-features = false }
rstest = "0.15.0"
serde = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1.20", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
tonic = { version = "0.8.0", default-features = false }
topos-core = { path = "./crates/topos-core", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
