networks:
  tce:
    ipam:
      config:
        - subnet: 192.168.55.0/24
services:
  tce-boot-node:
    build: .
    image: ghcr.io/toposware/tce:latest
    ports:
      - "1001:9090"
      - "8081:8080"
    networks:
      tce:
        ipv4_address: 192.168.55.11
    environment:
      - RUST_LOG=debug
      - TCE_LOCAL_KS=1 # 12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X
      - TCE_JAEGER_AGENT=nohost:6831
    command: 
      - "./topos-tce-node-app"
  peer2:
    build: .
    image: ghcr.io/toposware/tce:latest
    ports:
      - "1002:9090"
      - "8082:8080"
    networks:
      tce:
        ipv4_address: 192.168.55.12
    environment:
      - RUST_LOG=debug
      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/tce-boot-node/tcp/9090
      - TCE_JAEGER_AGENT=nohost:6831
    command:
      - "./topos-tce-node-app"
    depends_on:
      - tce-boot-node
#  peer3:
#    build: .
#    image: ghcr.io/toposware/tce:latest
#    ports:
#      - "1003:9090"
#      - "8083:8080"
#    networks:
#      tce:
#        ipv4_address: 192.168.55.13
#    environment:
#      - RUST_LOG=info
#      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/tce-boot-node/tcp/9090
#      - TCE_JAEGER_AGENT=nohost:6831
#    command:
#      - "./topos-tce-node-app"
#    depends_on:
#      - tce-boot-node
#  peer4:
#    build: .
#    image: ghcr.io/toposware/tce:latest
#    ports:
#      - "1004:9090"
#      - "8084:8080"
#    networks:
#      tce:
#        ipv4_address: 192.168.55.14
#    environment:
#      - RUST_LOG=info
#      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/tce-boot-node/tcp/9090
#      - TCE_JAEGER_AGENT=nohost:6831
#    command:
#      - "./topos-tce-node-app"
#    depends_on:
#      - tce-boot-node
#  peer5:
#    build: .
#    image: ghcr.io/toposware/tce:latest
#    ports:
#      - "1005:9090"
#      - "8085:8080"
#    networks:
#      tce:
#        ipv4_address: 192.168.55.15
#    environment:
#      - RUST_LOG=info
#      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/tce-boot-node/tcp/9090
#      - TCE_JAEGER_AGENT=nohost:6831
#    command:
#      - "./topos-tce-node-app"
#    depends_on:
#      - tce-boot-node
