services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "6831/udp"
      - "6832/udp"
      - "16685"
      - "16686:16686"
  boot:
    container_name: boot
    image: ghcr.io/toposware/tce:tools-ci-bug-fixes
    ports:
      - "9090"
      - "8080"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
      - TCE_LOCAL_KS=1 # 12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X
      - TCE_JAEGER_AGENT=jaeger:6831
    command:
      - "./topos-tce-node-app"
  peer:
    image: ghcr.io/toposware/tce:tools-ci-bug-fixes
    deploy:
      replicas: 5
    ports:
      - "9090"
      - "8080"
    environment:
      - RUST_LOG=info
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/boot/tcp/9090
    depends_on:
      - boot
  cert-spammer:
    container_name: spam
    image: ghcr.io/toposware/cert-spammer:main
    environment:
      - RUST_LOG=debug
      - TARGET_NODE=peer:8080
    depends_on:
      - jaeger
      - peer
