[package]
name = "topos-tce-transport"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
path = 'src/lib.rs'

[dependencies]
clap.workspace = true
serde = { workspace = true, features = ["rc"] }
tracing.workspace = true
topos-core = { workspace = true, features = ["api", "uci"] }
topos-crypto = { path = "../topos-crypto" }
