[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
clap.workspace = true
serde.workspace = true

topos-core = { workspace = true, features = ["uci"] }
topos-p2p = { path = "../topos-p2p/"}
topos-telemetry = { path = "../topos-telemetry/"}

tracing.workspace = true
opentelemetry = { version = "0.18", features = ["rt-tokio", "metrics"] }
