[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
serde.workspace = true
clap = { version = "3.0.10", features = ["derive", "env"] }

topos-core = { workspace = true, features = ["uci"] }

