[package]
name = "topos-tce-transport"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
serde.workspace = true
clap.workspace = true

topos-core = { workspace = true, features = ["uci"] }
topos-p2p = { path = "../topos-p2p/"}


