[package]
name = "topos-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
bincode.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio-stream.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

libp2p = { workspace = true, features = ["macros", "tcp", "dns", "tokio", "request-response", "identify", "mplex", "kad", "serde", "yamux"] }
void = "1"

[dev-dependencies]
test-log.workspace = true
env_logger.workspace = true
rstest = "0.15"
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

topos-test-sdk = { path = "../topos-test-sdk/", features = ["tce"] }
