[package]
name = "topos-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tracing.workspace = true
void = "1"
bincode.workspace = true

libp2p = { workspace = true, features = ["tcp-tokio", "dns-tokio", "request-response", "identify", "mplex", "mdns-tokio", "mdns", "kad", "serde"] }
tower.workspace = true

[dev-dependencies]
test-log.workspace = true
env_logger = "0.9.1"
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
