[package]
name = "topos-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tracing.workspace = true

libp2p = { workspace = true, features = ["tcp-tokio", "dns-tokio", "request-response", "identify", "mplex", "mdns-tokio", "mdns", "kad", "serde"] }

[dev-dependencies]
bincode = "1.3"
env_logger = "0.9.1"
test-log = { version = "0.2", features = ["trace"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
