[package]
name = "topos-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait.workspace = true
bincode.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true

libp2p = { workspace = true, features = ["macros", "tcp", "dns", "tokio", "request-response", "identify", "mplex", "kad", "serde"] }
void = "1"

[dev-dependencies]
test-log.workspace = true
env_logger.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
