[package]
name = "topos-uci"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
topos-crypto.workspace = true
ethereum-types.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
