[package]
name = "topos-uci"
version = "0.1.1"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { version = "1.0.136", features = ["derive"] }
ethereum-types = "0.12.1"
