[package]
name = "topos-uci"
version = "0.1.1"
edition = "2021"

[lints]
workspace = true

[dependencies]
topos-crypto.workspace = true
ethereum-types.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
