[package]
name = "topos-tce-synchronizer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tracing.workspace = true
topos-core = { workspace = true, features = ["api"] }

topos-p2p = { path = "../topos-p2p" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper/" }
uuid = { workspace = true, features = ["v4", "serde"] }
