[package]
name = "topos-tce-synchronizer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true


topos-api = { path = "../topos-api" }
topos-p2p = { path = "../topos-p2p" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper/" }
uuid = { version = "1.2.2", features = ["v4", "serde"] }

[dev-dependencies]
rstest = "0.16.0"
tokio-test = "0.4.2"
