[package]
name = "topos-tce-synchronizer"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "ansi", "fmt"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }

topos-core = { workspace = true, features = ["api"] }
topos-p2p = { path = "../topos-p2p" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper/" }
topos-tce-storage = { path = "../topos-tce-storage/" }

[dev-dependencies]
libp2p.workspace = true
mockall = "0.11"
async-trait.workspace = true
topos-test-sdk = { path = "../topos-test-sdk/" }
rstest.workspace = true

test-log.workspace = true

env_logger.workspace = true
