[package]
name = "topos-sequencer-subnet-client"
version = "0.1.0"
edition = "2021"

[dependencies]
topos-sequencer-types = { package = "topos-sequencer-types", path = "../topos-sequencer-types" }

hex.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
web3.workspace = true
secp256k1.workspace = true
tokio.workspace = true
topos-core = { workspace = true, features = ["uci"] }

ethereum-tx-sign = "6.0.0"
jsonrpsee-types = "0.14.0"
keccak-hash = "0.9"
tiny-keccak = "1.2"
