[package]
name = "topos-tce-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

topos-p2p = { path = "../topos-p2p" }
topos-core = { workspace = true, features = ["uci", "api"] }

async-stream = "0.3.3"
tonic-health = "0.7.0"
tonic-reflection = "0.5.0"
uuid = { version = "1.1.2", features = ["v4"] }

[dev-dependencies]
bytes = "1.2.1"
env_logger = "0.9.1"
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.20"
prost = "0.11.0"
test-log = { version = "0.2", features = ["trace"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
