[package]
name = "topos-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topos-uci = { path = "../topos-uci"}

tonic = { workspace = true, default-features = false, features = [
    "prost",
    "codegen",
    "transport",
] }
ethereum-types.workspace = true
uuid.workspace = true
prost = "0.11"
prost-types = "0.10"

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = [
    "prost", "transport"
] }

[dev-dependencies]
tokio.workspace = true
futures.workspace = true
tokio-stream.workspace = true
async-stream.workspace = true
tower = "0.4.13"
