[package]
name = "topos-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topos-uci = { path = "../topos-uci"}
tonic = { version = "0.8", default-features = false, features = [
    "prost",
    "codegen",
    "transport",
] }
prost = "0.11"
prost-types = "0.10"
ethereum-types = "0.13.1"
uuid = { version = "1.1.2", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = [
    "prost", "transport"
] }

[dev-dependencies]
async-stream = "0.3.3"
tower = "0.4.13"
tokio = "1.20.1"
tokio-stream = "0.1.9"
futures = "0.3.24"
