[package]
name = "topos-sequencer"
description = "Implementation of the Topos protocol"
license = "MIT"
version = "0.1.0"
authors = ["Toposware Developers <dev@toposware.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "3.0.10", features = ["derive", "env"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
tokio = { version = "1.15.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
    "sync",
] }
rpassword = "7.0.0"

topos-p2p = { path = "../topos-p2p/" }
topos-core = { workspace = true, features = ["uci"] }
topos-sequencer-api = { package = "topos-sequencer-api", path = "../topos-sequencer-api" }
topos-sequencer-certification = { package = "topos-sequencer-certification", path = "../topos-sequencer-certification" }
topos-sequencer-types = { package = "topos-sequencer-types", path = "../topos-sequencer-types" }
topos-sequencer-subnet-runtime-proxy = { package = "topos-sequencer-subnet-runtime-proxy", path = "../topos-sequencer-subnet-runtime-proxy" }
topos-sequencer-tce-proxy = { package = "topos-sequencer-tce-proxy", path = "../topos-sequencer-tce-proxy" }
