[package]
name = "topos-tce-broadcast"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
byteorder = "1.4.3"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
rand_distr = "0.4.1"
rand_core = "0.6.0"
rand = "0.8.5"
tokio-stream = { version = "*", features = ["sync"] }

serde.workspace = true
tokio.workspace = true
futures.workspace = true

topos-core = { workspace = true, features = ["uci"] }

tce_transport = { package = "topos-tce-transport", path = "../topos-tce-transport"}
tce_telemetry = { package = "topos-tce-telemetry", path = "../topos-tce-telemetry" }

tracing = "0.1"

[dev-dependencies]
pretty_env_logger = "0.4.0"
