[package]
name = "topos-tce-broadcast"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
futures.workspace = true
rand.workspace = true
rand_core.workspace = true
rand_distr.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
byteorder.workspace = true

topos-core = { workspace = true, features = ["uci"] }
topos-p2p = { path = "../topos-p2p/"}
tce_transport = { package = "topos-tce-transport", path = "../topos-tce-transport"}

opentelemetry = { version = "0.18", default-features = false, features = ["trace", "rt-tokio"] }
tracing-opentelemetry = "0.18"

[dev-dependencies]
