[package]
name = "topos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
topos-tce = { path = "../topos-tce/" }
topos-p2p = { path = "../topos-p2p" }
topos-tce-transport = { path = "../topos-tce-transport" }
topos-sequencer = { path = "../topos-sequencer" }

topos-core = { workspace = true, features = ["api"] }
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
opentelemetry = { version = "0.18", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = " 0.11", features = ["tonic", "metrics"] }
tracing-opentelemetry = "0.18.0"
tracing-attributes = "0.1.23"


uuid.workspace = true
clap.workspace = true
tower = "0.4.13"

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
assert_cmd = "2.0.6"
insta = { version = "1.21", features = ["json", "redactions"] }

