[package]
name = "topos"
version = "0.1.0"
edition = "2021"

[dependencies]
topos-core = { workspace = true, features = ["api"] }
topos-p2p = { path = "../topos-p2p" }
topos-sequencer = { path = "../topos-sequencer" }
topos-tce = { path = "../topos-tce/" }
topos-tce-transport = { path = "../topos-tce-transport" }

clap.workspace = true
futures.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic.workspace = true
tower.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
uuid.workspace = true

[dev-dependencies]
assert_cmd = "2.0.6"
insta = { version = "1.21", features = ["json", "redactions"] }
serde.workspace = true
serde_json.workspace = true

