[package]
name = "topos-sequencer-types"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
topos-core = { workspace = true, features = ["uci"] }

serde = { workspace = true, features = ["derive"] }
ethereum-types.workspace = true
