[package]
name = "topos-tce-node-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = 'src/lib.rs'

[dependencies]
bytes = "1.1.0"
hyper = { version = "0.14", features = ["full"] }
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tokio = { version = "1.20.0", features = [
    "io-util",
    "io-std",
    "macros",
    "rt",
    "rt-multi-thread",
    "fs",
    "time",
    "sync",
] }

tce_trbp = { package = "topos-tce-protocols-reliable-broadcast", path = "../../protocols/reliable_broadcast" }

topos-core = { git = "https://github.com/Toposware/topos-core", branch = "main", features = ["uci"], version = "0.1.0" }
