[alias]
xclippy = [
    "clippy", "--workspace", "--tests", "--all-targets", "--all-features", "--",
    "-Wclippy::all",
    "-Wclippy::disallowed-methods",
]

# https://nnethercote.github.io/perf-book/build-configuration.html#cpu-specific-instructions
[build]
rustflags = ["-C", "target-cpu=native"]
