[package]
name = "topos-clock"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tokio.workspace = true
futures.workspace = true
thiserror.workspace = true
chrono = {version = "0.4", default-features = false, features = ["clock"]}
tracing.workspace = true
