[package]
name = "topos-test-sdk"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
topos-core = { workspace = true, features = ["uci"] }
topos-tce-storage = { path = "../topos-tce-storage/" }
proc_macro_sdk = { path = "./proc_macro_sdk/" }
futures.workspace = true
