[package]
name = "topos-test-sdk"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lints]
workspace = true

[dependencies]
topos-core = { workspace = true, features = ["uci", "api"] }
topos-crypto = { path = "../topos-crypto/" }
topos-config = { path = "../topos-config/" }
topos-p2p = { path = "../topos-p2p/" }
topos-tce = { path = "../topos-tce/" }
topos-tce-api = { path = "../topos-tce-api/" }
topos-tce-broadcast = { path = "../topos-tce-broadcast/" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper/" }
topos-tce-storage = { path = "../topos-tce-storage/" }
topos-tce-synchronizer = { path = "../topos-tce-synchronizer/" }

hex.workspace = true
ethers.workspace = true
async-trait.workspace = true
futures.workspace = true
lazy_static = { version = "1.4.0" }
libp2p = { workspace = true, features = ["macros"] }
proc_macro_sdk = { path = "./proc_macro_sdk/" }
rand.workspace = true
rstest.workspace = true
tokio-stream.workspace = true
prost.workspace = true
tonic = { workspace = true, default-features = false, features = [
    "prost",
    "codegen",
    "transport",
] }

tower.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
async-stream.workspace = true

[build-dependencies]
tonic-build.workspace = true
