[profile.default]
slow-timeout = { period = "60s", terminate-after = 1 }
leak-timeout = "10s"

[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(serial_integration::)'
test-group = 'serial-integration'
