[package]
name = "topos-wallet"
description = "Key manager"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
secp256k1.workspace = true
byteorder.workspace = true
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true

keccak-hash = "0.10.0"
eth-keystore = "0.5.0"

topos-crypto.workspace = true
