[package]
name = "topos-tce"
description = "TCE Node Service"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bincode.workspace = true
clap.workspace = true
futures.workspace = true
opentelemetry.workspace = true
prometheus-client.workspace = true
prometheus.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
topos-core.workspace = true
tracing-attributes.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, default-features = false,  features = ["std", "env-filter", "fmt", "ansi"] }
tracing.workspace = true
tonic.workspace = true
bytes.workspace = true
prost.workspace = true

tce_transport = { package = "topos-tce-transport", path = "../topos-tce-transport" }
topos-p2p = { path = "../topos-p2p" }
topos-metrics = { path = "../topos-metrics" }
topos-tce-api = { path = "../topos-tce-api"}
topos-tce-broadcast = { path = "../topos-tce-broadcast" }
topos-tce-gatekeeper = { path = "../topos-tce-gatekeeper" }
topos-tce-storage = { package = "topos-tce-storage", path = "../topos-tce-storage" }
topos-tce-synchronizer = { path = "../topos-tce-synchronizer" }
topos-telemetry = { path = "../topos-telemetry" }
axum = "0.6.18"
axum-prometheus = "0.3.3"

[dev-dependencies]
async-stream.workspace = true
async-trait.workspace = true
hyper.workspace = true
libp2p.workspace = true
rand.workspace = true
rand_core.workspace = true
rand_distr.workspace = true
tonic.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
tracing.workspace = true
test-log.workspace = true
cucumber = "0.13.0"

[features]
default = []
log-json = ["tracing-subscriber/json"]

