services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "6831/udp"
      - "6832/udp"
      - "16685"
      - "16686:16686"
  boot:
    container_name: boot
    image: ghcr.io/toposware/tce:pr-4
    init: true
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=stable
        - GITHUB_TOKEN
    depends_on:
      - jaeger
    ports:
      - "9090"
    environment:
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - TCE_LOCAL_KS=1 # 12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X
      - TCE_JAEGER_SERVICE_NAME=tce-boot-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_TRBP_ECHO_SAMPLE_SIZE=3
      - TCE_TRBP_READY_SAMPLE_SIZE=3
      - TCE_TRBP_DELIVERY_SAMPLE_SIZE=3
      - TCE_TRBP_ECHO_THRESHOLD=3
      - TCE_TRBP_READY_THRESHOLD=3
      - TCE_TRBP_DELIVERY_THRESHOLD=3

  peer:
    image: ghcr.io/toposware/tce:pr-4
    init: true
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=stable
        - GITHUB_TOKEN
    depends_on:
      - jaeger
      - boot
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 5
    environment:
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_JAEGER_SERVICE_NAME=tce-regular-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/boot/tcp/9090
      - TCE_TRBP_ECHO_SAMPLE_SIZE=3
      - TCE_TRBP_READY_SAMPLE_SIZE=3
      - TCE_TRBP_DELIVERY_SAMPLE_SIZE=3
      - TCE_TRBP_ECHO_THRESHOLD=3
      - TCE_TRBP_READY_THRESHOLD=3
      - TCE_TRBP_DELIVERY_THRESHOLD=3

  cert-spammer:
    container_name: spam
    image: ghcr.io/toposware/cert-spammer:main
    init: true
    environment:
      - RUST_LOG=debug
      - TARGET_NODES_PATH=/nodes.json
    depends_on:
      - jaeger
      - peer
    volumes:
      - ./peer_nodes.json:/nodes.json
