services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831/udp"
      - "6832/udp"
      - "16685"
      - "16686:16686"
  boot:
    container_name: boot
    command: boot tce run -vv
    image: ghcr.io/toposware/tce:pr-4
    init: true
    healthcheck:
      test: ./topos tce push-peer-list --endpoint http://localhost:1340 --format json /tmp/shared/peer_ids.json
      interval: 5s
    volumes:
      - shared:/tmp/shared
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=stable
        - GITHUB_TOKEN
    depends_on:
      - jaeger
    ports:
      - "9090"
      - "1340"
    environment:
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_LOCAL_KS=1 # 12D3KooWRhFCXBhmsMnur3up3vJsDoqWh4c39PKXgSWwzAzDHNLn
      - TCE_JAEGER_SERVICE_NAME=tce-boot-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_ECHO_SAMPLE_SIZE=3
      - TCE_READY_SAMPLE_SIZE=3
      - TCE_DELIVERY_SAMPLE_SIZE=3
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=3
      - TCE_DELIVERY_THRESHOLD=3

  peer:
    image: ghcr.io/toposware/tce:pr-4
    command: tce run
    init: true
    healthcheck:
      test: ./topos tce push-peer-list --endpoint http://localhost:1340 --format json /tmp/shared/peer_ids.json
      interval: 5s
    volumes:
      - shared:/tmp/shared
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=stable
        - GITHUB_TOKEN
    depends_on:
      jaeger:
        condition: service_started
      boot:
        condition: service_healthy
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 10
    environment:
      - LOCAL_TEST_NET=true
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_JAEGER_SERVICE_NAME=tce-regular-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_BOOT_PEERS=12D3KooWRhFCXBhmsMnur3up3vJsDoqWh4c39PKXgSWwzAzDHNLn /dns4/boot/tcp/9090
      - TCE_ECHO_SAMPLE_SIZE=3
      - TCE_READY_SAMPLE_SIZE=3
      - TCE_DELIVERY_SAMPLE_SIZE=3
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=3
      - TCE_DELIVERY_THRESHOLD=3

  cert-spammer:
    container_name: spam
    image: ghcr.io/toposware/cert-spammer:main
    init: true
    volumes:
      - shared:/tmp/shared
    environment:
      - RUST_LOG=info
      - TARGET_NODES_PATH=/tmp/shared/peer_nodes.json
    depends_on:
      jaeger:
        condition: service_started
      peer:
        condition: service_healthy

volumes:
  shared:
