services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14250:14250"
      - "16685:16685"

  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  boot:
    container_name: boot
    image: tce:develop
    init: true
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=${TOOLCHAIN_VERSION}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - otel-collector
    ports:
      - "9090"
    environment:
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - TCE_LOCAL_KS=1 # 12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X
      - TCE_JAEGER_SERVICE_NAME=tce-boot-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_TRBP_ECHO_SAMPLE_SIZE=3
      - TCE_TRBP_READY_SAMPLE_SIZE=3
      - TCE_TRBP_DELIVERY_SAMPLE_SIZE=3
      - TCE_TRBP_ECHO_THRESHOLD=3
      - TCE_TRBP_READY_THRESHOLD=3
      - TCE_TRBP_DELIVERY_THRESHOLD=3

  peer:
    image: tce:develop
    init: true
    build:
      context: ../
      args:
        - TOOLCHAIN_VERSION=${TOOLCHAIN_VERSION}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - otel-collector
      - boot
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 5
    environment:
      - RUST_LOG=info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_JAEGER_SERVICE_NAME=tce-regular-node
      - TCE_JAEGER_AGENT=jaeger:6831
      - TCE_BOOT_PEERS=12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X /dns4/boot/tcp/9090
      - TCE_TRBP_ECHO_SAMPLE_SIZE=3
      - TCE_TRBP_READY_SAMPLE_SIZE=3
      - TCE_TRBP_DELIVERY_SAMPLE_SIZE=3
      - TCE_TRBP_ECHO_THRESHOLD=3
      - TCE_TRBP_READY_THRESHOLD=3
      - TCE_TRBP_DELIVERY_THRESHOLD=3

  cert-spammer:
    container_name: spam
    image: ghcr.io/toposware/cert-spammer:main
    init: true
    environment:
      - RUST_LOG=debug
      - TARGET_NODES_PATH=/nodes.json
    depends_on:
      - otel-collector
      - peer
    volumes:
      - ./peer_nodes.json:/nodes.json
