helmDefaults:
  wait: true

repositories:
 - name: toposware
   url: https://raw.githubusercontent.com/toposware/helm-charts/gh-pages/
   username: {{ requiredEnv "GITHUB_USERNAME"}}
   password: {{ requiredEnv "GITHUB_TOKEN"}}
 - name: aws-efs-csi-driver
   url: https://kubernetes-sigs.github.io/aws-efs-csi-driver

releases:
- name: aws-efs-csi-driver
  namespace: kube-system
  chart: aws-efs-csi-driver/aws-efs-csi-driver
  version: 2.3.6
  createNamespace: true
  set:
  - name: controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
    value: arn:aws:iam::367397670706:role/cicd-devnet-1-eks-efs-csi-irsa
