helmDefaults:
  wait: true
  timeout: 600

repositories:
 - name: toposware
   url: https://raw.githubusercontent.com/toposware/helm-charts/gh-pages/
   username: {{ requiredEnv "GITHUB_USERNAME"}}
   password: {{ requiredEnv "GITHUB_TOKEN"}}
 - name: aws-efs-csi-driver
   url: https://kubernetes-sigs.github.io/aws-efs-csi-driver
 - name: bitnami
   url: https://charts.bitnami.com/bitnami
 - name: ingress-nginx
   url: https://kubernetes.github.io/ingress-nginx
 - name: jetstack
   url: https://charts.jetstack.io

releases:
- name: aws-efs-csi-driver
  namespace: kube-system
  chart: aws-efs-csi-driver/aws-efs-csi-driver
  version: 2.3.6
  createNamespace: true
  set:
  - name: controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
    value: {{ requiredEnv "EKS_EFS_CSI_IRSA_ARN" }}

- name: nginx
  namespace: ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.4.2
  createNamespace: true
  set:
  - name: controller.replicaCount
    value: 2

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.10.1
  createNamespace: true
  needs:
  - ingress/nginx
  set:
  - name: installCRDs
    value: true

- name: external-dns
  namespace: kube-system
  chart: bitnami/external-dns
  version: 6.12.3
  needs:
  - ingress/nginx
  set:
  - name: provider
    value: aws
  - name: aws.zoneType
    value: public
  - name: txtOwnerId
    value: Z068685927XPZYR30SPU2
  - name: domainFilters[0]
    value: tce.devnet-1.toposware.com
  - name: serviceAccount.create
    value: true
  - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
    value: {{ requiredEnv "EKS_EXTERNAL_DNS_IRSA_ARN" }}

- name: tce-tmp-storage
  namespace: default
  chart: toposware/tce-tmp-storage
  version: 0.1.0
  createNamespace: true
  needs:
  - kube-system/aws-efs-csi-driver
  set:
  - name: fileSystemId
    value: {{ requiredEnv "FILESYSTEM_ID" }}

- name: tce-all-in-one
  namespace: default
  chart: toposware/tce-all-in-one
  version: 0.1.24
  createNamespace: true
  needs:
  - tce-tmp-storage
  set:
  - name: image.repository
    value: ghcr.io/toposware/topos
  - name: peerReplicas
    value: 15
  - name: image.tag
    value: {{ requiredEnv "DOCKER_TAG"}}
  - name: credentials.username
    value: {{ requiredEnv "DOCKER_USERNAME"}}
  - name: credentials.password
    value: {{ requiredEnv "DOCKER_PASSWORD"}}
  - name: otelEndpoint
    value: https://otel-collector.telemetry.devnet-1.toposware.com:443
  - name: bootHost
    value: boot\.tce\.devnet-1\.toposware\.com
  - name: peersHost
    value: peers\.tce\.devnet-1\.toposware\.com
  - name: acme.environment
    value: production
  - name: acme.email
    value: thiago.nobayashi@toposware.com
  - name: ingress
    value: true
  - name: certSpammer
    value: false
