receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 1m
    scrapers:
      load:
      memory:

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
    timeout: 1s

extensions:
  health_check:

exporters:
  otlp/elastic:
    apm_server_url: "http://localhost:8220"

  logging:
    loglevel: info

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - otlp/elastic
