[package]
name = "topos-tce-telemetry"
version = "0.1.0"
edition = "2021"

[lib]
path = 'src/lib.rs'

[dependencies]
tracing.workspace = true

topos-core = { workspace = true, features = ["uci"] }

lazy_static = "1.4"
opentelemetry = { version = "0.17", default-features = false, features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.16", features = ["rt-tokio"] }
