name: Docker_build_push

on:
  push:
    branches: [debug/**]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      git_commit:
        required: true
        type: string
      docker_tag:
        required: true
        type: string

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      tag: "${{ inputs.docker_tag }}"

  direct:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      features: "tce-direct,sequencer"

  k8s_e2e:
    if: ${{ github.event_name == 'workflow_dispatch' ||  github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Set environment
        run: |
          # It's fine to assume index 0. The type=raw has higher priority
          tags=${{ fromJson(steps.meta.outputs.json).tags[0] }}
          echo "docker_tag=${tags#*:}" >> $GITHUB_ENV
        shell: bash

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: toposware
          repo: k8s-e2e
          github_token: ${{ secrets.ROBOT_TOPOSWARE_K8S_E2E_RW }}
          workflow_file_name: test.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "git_commit": "${{ inputs.git_commit }}", "docker_tag": "${{ env.docker_tag }}" }'
