name: Docker_build_push

on:
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit

  direct:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      features: "tce-direct,sequencer"
