name: Docker_build_push

on:
  pull_request:
    branches: [main]

permissions: write-all

jobs:
  docker:
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit

  direct:
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit
    with:
      features: "tce-direct,sequencer"

  trigger:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    # needs: docker
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'toposware',
              repo: 'k8s-e2e',
              workflow_id: 'test.yml',
              ref: 'main'
            })
