name: Docker_build_push

on:
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit

  direct:
    uses: toposware/topos/.github/workflows/docker_utils.yml@main
    secrets: inherit
    with:
      features: "tce-direct,sequencer"


