name: Docker_build_push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit

  direct:
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      features: "tce-direct,sequencer"

  k8s_e2e:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Set environment
        run: |
          sha=${{ github.sha }}
          uid="${sha:0:6}-${{ github.run_number }}"
          echo "UID=${uid}" >> $GITHUB_ENV
        shell: bash

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: toposware
          repo: k8s-e2e
          github_token: ${{ secrets.ROBOT_TOPOSWARE_K8S_E2E_RW }}
          workflow_file_name: test.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "uid": "${{ env.UID }}"}'
