name: Docker and Kubernetes jobs

on:
  push:
    branches:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Build and push docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
#  k8s:
#    name: Deploy k8s cluster and run TCE network
#    needs: docker
#    runs-on: ubuntu-latest
#    container:
#      image: hashicorp/terraform:1.2.4
#    permissions:
#      contents: read
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Terraform init
#        run: terraform -chdir=./tools/terraform init
#      - name: Terraform plan
#        run: terraform -chdir=./tools/terraform plan -var="cluster_name=${{ github.sha }}" -var="docker_image=${{ needs.docker.outputs.docker_tag }}"
