name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  fmt:
    strategy:
      fail-fast: false
      matrix:
        version: [stable]
    name: ${{ matrix.version }} - Check format
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      target: fmt
      toolchain_version: ${{ matrix.version }}
