name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        version: [stable]
    name: ${{ matrix.version }} - Lint
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      target: lint
      toolchain_version: ${{ matrix.version }}

  msrv:
    name: MSRV check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/install-rust
        with:
          msrv: true
          AWS_ACCESS_KEY_ID: ${{ secrets.ROBOT_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ROBOT_AWS_SECRET_ACCESS_KEY}}

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
