name: Checking PR semantic

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commits:
    name: Validate PR commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  labels:
    name: Verify PR labels
    runs-on: ubuntu-latest
    steps:
      - name: Verify if PR has the "ok-to-merge" label
        uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const label of labels.data) {
              if (label.name == 'ok-to-merge') {
                return;
              }
            }

            core.setFailed();
