name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
        version:
          - stable
          - nightly-2022-07-20

    name: ${{ matrix.version }} - Test
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          target: test
          build-args: |
            GITHUB_TOKEN=${{ secrets.ROBOT_TOPOSWARE_GH_PACKAGE_TOKEN }}
            TOOLCHAIN_VERSION=${{ matrix.version }}
