name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [stable, nightly]
    name: ${{ matrix.version }} - Test
    uses: ./.github/workflows/docker_utils.yml
    secrets: inherit
    with:
      target: test
      toolchain_version: ${{ matrix.version }}
